language: node_js
dist: trusty
node_js:
  - "8"
  - "9"
  - "10"
  - "11"
jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: npm install coveralls istanbul mocha-lcov-reporter && istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec tests && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage