language: node_js
dist: trusty
node_js:
  - "8"
  - "9"
  - "10"
  - "11"
jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: npm install coveralls blanket mocha-lcov-reporter && mocha --require blanket --reporter mocha-lcov-reporter tests | ./node_modules/coveralls/bin/coveralls.js